### ISSUE TITLE
snyk ignore command does not work without calling snyk auth first on Jenkins pipelines

### ISSUE THREAD

**Issue by leonickel** [snyk/cli#556] opened 2019-06-05 13:00 UTC
- `node -v`: v8.16.0
- `npm -v`: 6.4.1
- `snyk -v`: 1.171.1
- Command run:
```snyk ignore --id='SNYK-JAVA-COMMONSBEANUTILS-30077'```

### Expected behaviour
Since the `env` variable `SNYK_TOKEN` is set and the command `snyk test` works fine already, I expected that the `snyk ignore` would also work.

### Actual behaviour
When running `snyk ignore` i'm getting the following error:
```
snyk ignore --id=SNYK-JAVA-COMMONSBEANUTILS-30077
Web auth cannot be used whilst inside CI. You must include your API token as an environment value: `API=12345678`
```
In the very same context, if i run `snyk test` it works.
**Workaround:** in order to make it work, i had to add the command `snyk auth $SNYK_TOKEN` before running `snyk ignore`. 

### Steps to reproduce
- setup `snyk` integration in your Jenkins pipeline. By that i mean installing `snyk` and having `SNYK_TOKEN` env set;
- run `snyk test` to make sure snyk works;
- add `snyk ignore` command and re-run the pipeline. It would fail due to authentication issue.

**Comment by dominykas** [comment] 2022-01-12 16:23
I've recently run into this:

```
$ CI=true SNYK_TOKEN=(redacted) snyk ignore --id="snyk:lic:npm:commercial:hapi:Unknown" --expiry='2023-01-04T00:00:00.000Z' --reason='We have a commercial hapi license'
Snyk is missing auth token in order to run inside CI. You must include your API token as an environment value: `SNYK_TOKEN=12345678`
```

Workaround:

```
$ CI=true SNYK_CFG_API=(redacted) snyk ignore --id="snyk:lic:npm:commercial:hapi:Unknown" --expiry='2023-01-04T00:00:00.000Z' --reason='We have a commercial hapi license'
```

It seems the authentication handling in CLI code could use some cleanup for consistency.

**Comment by JackuB** [comment] 2022-03-15 12:53
I believe this behavior is by design, those commands require you to have Snyk API token setup. Closing this issue as we are not using GitHub issues for tracking feature requests.

See https://docs.snyk.io/ for Snyk products documentation
Please reach out to https://support.snyk.io/ for Snyk product questions.

**Closed by JackuB** 2022-03-15 12:53 UTC
Labels: :bug:  bug, jenkins

**Comment by robmcgee-isw** [comment] 2023-08-30 19:52
@JackuB Why would the `snyk ignore` command even need to authenticate? Isn't it just creating a local ~/.snyk file? 
Other commands like `synk monitor` work fine without pre-auth..
